[package]
name = "exchanges"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "matching_engine_burst"
path = "bin/matching_engine_burst.rs"

[[bin]]
name = "exchange_burst"
path = "bin/exchange_burst.rs"

[dependencies]
anyhow = "1.0.98"
rand = "0.9.0"
